# escape=`
ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-windowsservercore-ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV PYTHONDONTWRITEBYTECODE=1 `
    PYTHONUNBUFFERED=1 `
    ARKA_AUTO_REFETCH=0

WORKDIR C:/app

COPY pyproject.toml README.md ./
COPY src ./src

RUN pip install --no-cache-dir -e ".[dev]"

CMD ["python", "-m", "arka", "--version"]
