"""Tests for compose_3d — NL parsing and procedural mesh generation."""

from __future__ import annotations

import pytest

from arka.media.compose_3d import (
    generate_cube,
    generate_gear,
    generate_sphere,
    generate_vase,
    nl_to_argv,
    parse_obj,
    route_command,
    save_mesh,
    slugify,
    write_obj,
    write_stl,
)


def test_nl_to_argv_create_3d_gear():
    assert nl_to_argv("create a 3d model of a gear") == ["gear", "--name", "gear"]


def test_nl_to_argv_create_an_3d_boy():
    assert nl_to_argv("create an 3d model of an boy") == ["boy"]


def test_nl_to_argv_create_a_3d_model_of_a_boy():
    assert nl_to_argv("create a 3d model of a boy") == ["boy"]


def test_nl_to_argv_fish_escaped_quotes():
    assert nl_to_argv("'create an 3d model of an boy'") == ["boy"]


def test_route_command_boy():
    assert route_command("create an 3d model of an boy") == "compose_3d boy"


def test_nl_to_argv_make_3d_vase_with_height():
    argv = nl_to_argv("make 3d vase 10cm tall")
    assert argv[0] == "vase"
    assert "--height" in argv
    assert float(argv[argv.index("--height") + 1]) == pytest.approx(0.1)


def test_nl_to_argv_compose_3d_coffee_mug():
    argv = nl_to_argv("compose 3d model of a coffee mug")
    assert argv[0] == "cylinder"
    assert "--radius" in argv
    assert "--height" in argv


def test_nl_to_argv_generate_stl_phone_stand():
    argv = nl_to_argv("generate stl for phone stand")
    assert argv[0] == "cube"
    assert "--format" in argv
    assert argv[argv.index("--format") + 1] == "stl"


def test_nl_to_argv_sphere():
    assert nl_to_argv("3d sphere radius 2") == ["sphere", "--radius", "2"]


def test_nl_to_argv_not_matched():
    assert nl_to_argv("what is kubernetes") == []


def test_route_command():
    assert route_command("make 3d gear") == "compose_3d gear --name gear"


def test_slugify():
    assert slugify("Coffee Mug!") == "coffee_mug"


def test_generate_cube_mesh():
    vertices, faces = generate_cube(2.0, 1.0, 0.5)
    assert len(vertices) == 8
    assert len(faces) == 12
    obj = write_obj(vertices, faces)
    assert obj.startswith("# Generated by Arka compose_3d")
    assert "v " in obj
    assert "f " in obj


def test_generate_sphere_mesh():
    vertices, faces = generate_sphere(radius=1.0, segments=8, rings=8)
    assert len(vertices) > 10
    assert len(faces) > 10
    stl = write_stl(vertices, faces, "sphere")
    assert stl.startswith("solid sphere")
    assert "facet normal" in stl


def test_generate_gear_mesh():
    vertices, faces = generate_gear(teeth=8, segments=32)
    assert len(vertices) > 20
    assert len(faces) > 20


def test_generate_vase_mesh():
    vertices, faces = generate_vase(height=0.15, segments=16, rings=12)
    assert len(vertices) > 50
    assert len(faces) > 50


def test_save_mesh_writes_obj_and_stl(tmp_path, monkeypatch):
    monkeypatch.setenv("MODEL_3D_OUTPUT_DIR", str(tmp_path))
    vertices, faces = generate_cube()
    saved = save_mesh(vertices=vertices, faces=faces, name="test_cube", formats={"obj", "stl"})
    assert saved["obj"].exists()
    assert saved["stl"].exists()
    parsed_vertices, parsed_faces = parse_obj(saved["obj"].read_text(encoding="utf-8"))
    assert len(parsed_vertices) == 8
    assert len(parsed_faces) == 12


def test_parse_obj_quad_triangulation():
    obj = "\n".join(
        [
            "v 0 0 0",
            "v 1 0 0",
            "v 1 1 0",
            "v 0 1 0",
            "f 1 2 3 4",
        ]
    )
    vertices, faces = parse_obj(obj)
    assert len(vertices) == 4
    assert len(faces) == 2
