"""Create safe .env templates without fabricating credentials."""
from __future__ import annotations
import argparse
import re
from pathlib import Path

_ENV_REF = re.compile(r"\bos\.environ(?:\.get)?\(\s*['\"]([A-Z][A-Z0-9_]+)")
_DOLLAR_REF = re.compile(r"\$\{([A-Z][A-Z0-9_]+)\}")
_SECRET = re.compile(r"(?i)(key|token|secret|password|credential)")

def required_env(root: Path) -> list[str]:
    found: set[str] = set()
    for path in root.rglob("*"):
        if not path.is_file() or any(p in {".git", ".venv", "venv", "node_modules"} for p in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        found.update(_ENV_REF.findall(text))
        found.update(_DOLLAR_REF.findall(text))
    return sorted(found)

def create_env(root: Path, *, output: Path | None = None, force: bool = False) -> Path:
    dest = output or root / ".env"
    existing = dest.read_text(encoding="utf-8") if dest.is_file() else ""
    current = {m.group(1) for m in re.finditer(r"^([A-Z][A-Z0-9_]*)=", existing, re.M)}
    keys = required_env(root)
    lines = [existing.rstrip()] if existing.strip() else ["# Generated by Arka; fill credentials manually."]
    for key in keys:
        if key not in current:
            hint = "your-secret-here" if _SECRET.search(key) else ""
            lines.append(f"{key}={hint}")
    if dest.exists() and not force and not existing.strip():
        raise FileExistsError(f"Refusing to overwrite {dest}; use --force")
    dest.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return dest

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate a safe .env template using local project inspection")
    p.add_argument("path", nargs="?", default=".")
    p.add_argument("--output")
    p.add_argument("--force", action="store_true")
    args = p.parse_args(argv)
    try:
        print(create_env(Path(args.path).expanduser().resolve(), output=Path(args.output).expanduser() if args.output else None, force=args.force))
    except FileExistsError as exc:
        p.error(str(exc))
    return 0
